server:
  port: 8989
  shutdown: graceful

spring:

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://127.0.0.1:9000"
      client:
        registration:
          api-gateway:
            provider: spring
            client-id: api-gateway-client-id
            client-secret: 12345-client-secret
            authorization-grant-type: authorization_code
            redirect_uri: "http://127.0.0.1:8989/user/userlist"
            scope:
              - openid
              - profile
              - read
            client-name: api-gateway
        provider:
          spring:
            issuer-uri: "http://127.0.0.1:9000"
  cloud:
    gateway:
      routes:
        - id: user
          uri:  http://localhost:8082
          predicates:
            - Path=/user/**
  application:
    name: api-gateway
